### ISSUE TITLE
Błąd: po odświeżeniu strony następuje wylogowanie i trzeba się logować od nowa

### ISSUE THREAD

**Issue by mberkan** [gildia-sc/hackyeah#47]
Tomek, wydaje nam się że przed Twoją zmianą #42 działało to lepiej.

**Comment by tarczynskitomek** [comment]
@mberkan zmiana #42 nie popsuła tego, tylko bardziej uwidoczniła prorblem, front gubił informacje o sesji już wcześniej.

Naprawiłem dodając sprawdzanie sesji po stronie backendu przy odświeżeniu / przeładowaniu strony.
